#!/bin/bash
# My downloader script

echo "Beginning process..."

echo "--enter folder name to download to--------------------------"
read FOLDER 
echo "You entered: $FOLDER"

echo "Grabbing youtube-dl"
command -v youtube-dl >/dev/null 2>&1 || sudo apt install youtube-dl

echo "Assuming that one of ffmpeg or avconv and ffprobe or avprobe are installed on your machine. TIP: You can `brew install ffmpeg`"

echo "Cleaning your links.txt list: i.e. removing all duplicated and non-links"
pip install --upgrade validators
python remDup.py

echo "Downloading music in links.txt to new folder $FOLDER in the current directory $PWD"

trap '{ echo "Hey, you pressed Ctrl-C :(" ; exit 1; }' INT

while read p; do
	# Downloading each individual song- parse songs names here
	if [[ $p == *"soundcloud"* ]] 
	then
		echo $p
		SAVENAME=${p##*soundcloud.com/}
		SAVENAME=${SAVENAME//-/ }
		SAVENAME=${SAVENAME//// > }
		echo $SAVENAME
		youtube-dl --extract-audio --audio-format mp3 -o "$FOLDER/$SAVENAME.%(ext)s" $p --no-cache-dir
		unset SAVENAME
	else
		youtube-dl --extract-audio --audio-format mp3 -o "$FOLDER/%(title)s.%(ext)s" $p --no-cache-dir
	fi
done < links.txt
